# .scrutinizer.yml
filter:
    excluded_paths:
        - tests/*
checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cpd: true
    php_analyzer: true
    php_pdepend: true
    php_sim: true
    php_mess_detector: true
