<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb27e85a68c18d0f978705ef2d0c4a7b3
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WebSocket\\' => 10,
        ),
        'S' => 
        array (
            'SocketCluster\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WebSocket\\' => 
        array (
            0 => __DIR__ . '/..' . '/textalk/websocket/lib',
        ),
        'SocketCluster\\' => 
        array (
            0 => __DIR__ . '/..' . '/soleon/sc-php/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb27e85a68c18d0f978705ef2d0c4a7b3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb27e85a68c18d0f978705ef2d0c4a7b3::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
