<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WebSocket\\' => array($vendorDir . '/textalk/websocket/lib'),
    'SocketCluster\\' => array($vendorDir . '/soleon/sc-php/src'),
);
